#%RAML 1.0 NamedExample
value:
  -
    name: Samantha Jones
    type: business
    address: "5th Avenue,55,New York,NY,55000,USA"
    air_miles: 900
  - 
    name: Michael Smith
    type: personal
    address: "Green St,27,Los Angeles,CA,92000,USA"
    air_miles: 700